import React, { useState } from 'react';
import { FileText, Download, Play, Volume2, Copy, Share } from 'lucide-react';

const ActionControlsPanel = ({
    sessionId,
    activeDocumentId,
    selectedText,
    activeDocument
}) => {
    const [generating, setGenerating] = useState(false);
    const [summary, setSummary] = useState('');
    const [audioUrl, setAudioUrl] = useState(null);

    const handleSummarize = async () => {
        setGenerating(true);

        try {
            // Simulate summary generation
            await new Promise(resolve => setTimeout(resolve, 2000));

            if (selectedText) {
                setSummary(`Summary of selected text: "${selectedText.substring(0, 100)}..."\n\nThis is a demo summary that would be generated by the LLM service based on the selected text.`);
            } else {
                setSummary(`Document Summary: ${activeDocument?.title}\n\nThis is a demo summary of the entire document that would be generated by the LLM service.`);
            }
        } catch (error) {
            console.error('Failed to generate summary:', error);
        } finally {
            setGenerating(false);
        }
    };

    const handleGeneratePodcast = async () => {
        setGenerating(true);

        try {
            // Simulate podcast generation
            await new Promise(resolve => setTimeout(resolve, 3000));

            // This would normally call the backend to generate audio
            setAudioUrl('demo-podcast.mp3'); // Demo URL
        } catch (error) {
            console.error('Failed to generate podcast:', error);
        } finally {
            setGenerating(false);
        }
    };

    const handleCopy = () => {
        if (summary) {
            navigator.clipboard.writeText(summary);
        }
    };

    const handleDownload = () => {
        if (summary) {
            const blob = new Blob([summary], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `summary-${activeDocument?.title || 'document'}.txt`;
            a.click();
            URL.revokeObjectURL(url);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center">
                <h3 className="text-lg font-semibold text-gray-800 flex items-center">
                    <FileText className="h-5 w-5 mr-2 text-orange-600" />
                    Actions
                </h3>
            </div>

            {!activeDocumentId ? (
                <div className="text-center py-8">
                    <FileText className="h-12 w-12 text-gray-300 mx-auto mb-3" />
                    <p className="text-gray-500">Select a document to see available actions</p>
                </div>
            ) : (
                <div className="space-y-4">
                    {/* Summary Section */}
                    <div className="bg-white border border-gray-200 rounded-lg p-4">
                        <div className="flex items-center justify-between mb-3">
                            <h4 className="font-medium text-gray-700">
                                {selectedText ? 'Summarize Selection' : 'Summarize Document'}
                            </h4>
                            <button
                                onClick={handleSummarize}
                                disabled={generating}
                                className={`
                  px-3 py-1 rounded-md text-sm font-medium transition-colors
                  ${generating
                                        ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                                        : 'bg-blue-600 text-white hover:bg-blue-700'
                                    }
                `}
                            >
                                {generating ? 'Generating...' : 'Generate'}
                            </button>
                        </div>

                        {selectedText && (
                            <div className="mb-3 p-3 bg-blue-50 rounded-lg">
                                <p className="text-sm text-blue-800 font-medium mb-1">Selected Text:</p>
                                <p className="text-sm text-blue-700">
                                    "{selectedText.length > 150 ? selectedText.substring(0, 150) + '...' : selectedText}"
                                </p>
                            </div>
                        )}

                        {summary && (
                            <div className="space-y-3">
                                <div className="p-3 bg-gray-50 rounded-lg">
                                    <p className="text-sm text-gray-700 whitespace-pre-wrap">{summary}</p>
                                </div>

                                <div className="flex space-x-2">
                                    <button
                                        onClick={handleCopy}
                                        className="flex items-center px-3 py-1 text-sm text-gray-600 hover:text-gray-800 border border-gray-300 rounded-md hover:bg-gray-50"
                                    >
                                        <Copy className="h-4 w-4 mr-1" />
                                        Copy
                                    </button>
                                    <button
                                        onClick={handleDownload}
                                        className="flex items-center px-3 py-1 text-sm text-gray-600 hover:text-gray-800 border border-gray-300 rounded-md hover:bg-gray-50"
                                    >
                                        <Download className="h-4 w-4 mr-1" />
                                        Download
                                    </button>
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Podcast Generation */}
                    <div className="bg-white border border-gray-200 rounded-lg p-4">
                        <div className="flex items-center justify-between mb-3">
                            <h4 className="font-medium text-gray-700">Generate Podcast</h4>
                            <button
                                onClick={handleGeneratePodcast}
                                disabled={generating}
                                className={`
                  px-3 py-1 rounded-md text-sm font-medium transition-colors
                  ${generating
                                        ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                                        : 'bg-green-600 text-white hover:bg-green-700'
                                    }
                `}
                            >
                                {generating ? 'Generating...' : 'Generate'}
                            </button>
                        </div>

                        <p className="text-sm text-gray-600 mb-3">
                            Create an AI-generated podcast from this document with natural conversation flow.
                        </p>

                        {audioUrl && (
                            <div className="space-y-3">
                                <div className="bg-green-50 border border-green-200 rounded-lg p-3">
                                    <div className="flex items-center mb-2">
                                        <Volume2 className="h-4 w-4 text-green-600 mr-2" />
                                        <span className="text-sm font-medium text-green-800">Podcast Ready!</span>
                                    </div>

                                    {/* Audio Player (Demo) */}
                                    <div className="bg-white rounded-lg p-3 border">
                                        <div className="flex items-center space-x-3">
                                            <button className="p-2 bg-green-600 text-white rounded-full hover:bg-green-700">
                                                <Play className="h-4 w-4" />
                                            </button>
                                            <div className="flex-1">
                                                <div className="w-full bg-gray-200 rounded-full h-2">
                                                    <div className="bg-green-600 h-2 rounded-full" style={{ width: '0%' }}></div>
                                                </div>
                                                <div className="flex justify-between text-xs text-gray-500 mt-1">
                                                    <span>0:00</span>
                                                    <span>5:23</span>
                                                </div>
                                            </div>
                                            <button className="p-2 text-gray-600 hover:text-gray-800">
                                                <Download className="h-4 w-4" />
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Document Info */}
                    <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
                        <h4 className="font-medium text-gray-700 mb-3">Document Info</h4>
                        <div className="space-y-2 text-sm">
                            <div className="flex justify-between">
                                <span className="text-gray-600">Title:</span>
                                <span className="text-gray-800 font-medium">{activeDocument?.title}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-gray-600">Pages:</span>
                                <span className="text-gray-800">{activeDocument?.total_pages || 0}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-gray-600">Status:</span>
                                <span className={`
                  font-medium
                  ${activeDocument?.processing_status === 'completed'
                                        ? 'text-green-600'
                                        : activeDocument?.processing_status === 'processing'
                                            ? 'text-yellow-600'
                                            : 'text-red-600'
                                    }
                `}>
                                    {activeDocument?.processing_status || 'Unknown'}
                                </span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-gray-600">Uploaded:</span>
                                <span className="text-gray-800">
                                    {activeDocument?.upload_timestamp
                                        ? new Date(activeDocument.upload_timestamp).toLocaleDateString()
                                        : 'Unknown'
                                    }
                                </span>
                            </div>
                        </div>
                    </div>

                    {/* Quick Actions */}
                    <div className="bg-white border border-gray-200 rounded-lg p-4">
                        <h4 className="font-medium text-gray-700 mb-3">Quick Actions</h4>
                        <div className="grid grid-cols-2 gap-2">
                            <button className="flex items-center justify-center px-3 py-2 text-sm text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50">
                                <Share className="h-4 w-4 mr-1" />
                                Share
                            </button>
                            <button className="flex items-center justify-center px-3 py-2 text-sm text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50">
                                <Download className="h-4 w-4 mr-1" />
                                Export
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ActionControlsPanel;
