#!/bin/bash

cat > /app/.env <<EOL
GEMINI_API_KEY=${GEMINI_API_KEY:-}
GEMINI_TTS_MODEL=${GEMINI_TTS_MODEL:-gemini-3.1-flash-tts-preview}
GEMINI_TTS_HOST_VOICE=${GEMINI_TTS_HOST_VOICE:-Kore}
GEMINI_TTS_GUEST_VOICE=${GEMINI_TTS_GUEST_VOICE:-Puck}

LLM_PROVIDER=${LLM_PROVIDER:-gemini}
GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}

SESSION_TIMEOUT_HOURS=${SESSION_TIMEOUT_HOURS:-4}
MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-50}
SPEED_PRIORITY=${SPEED_PRIORITY:-high}
ACCURACY_MINIMUM=${ACCURACY_MINIMUM:-0.85}
EOL

echo "Environment file created"
echo "LLM Provider: $LLM_PROVIDER"
echo "Session Timeout: $SESSION_TIMEOUT_HOURS hours"
echo "Max File Size: $MAX_FILE_SIZE_MB MB"

exec "$@"
